name: nto_final_eco_containers_net
description: Веб-приложение для сети эко-контейнеров. Для финала НТО.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^0.13.4
  material_design_icons_flutter: ^5.0.6595
  crypto: ^3.0.1
  intl: ^0.17.0
  excel:
    git:
      url: https://github.com/justkawal/excel.git
      ref: null-safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/